### PR TITLE
test(e2e): migrate template alias tests to sdk_compat framework

### PR DESCRIPTION
**Pull request by sparkzky**
## Summary

Migrates template alias e2e tests from the standalone `sdk/python/tests/test_template_e2e.py` into the `tests/e2e/sdk_compat/` framework introduced by #835.

Follow-up to #749 (template alias feature, merged).

## Changes

| File | Change |
|---|---|
| `sdk/python/tests/test_template_e2e.py` | **Deleted** — old standalone test file |
| `tests/e2e/sdk_compat/cases/templates/test_alias.py` | **New** — 6 tests using CubeSandbox SDK |
| `tests/e2e/sdk_compat/cases/templates/__init__.py` | **New** — package init |
| `tests/e2e/sdk_compat/pytest.ini` | Added `templates` marker |

No changes to `framework/config.py`. Container image (`sandbox-code:latest`) and writable layer size (`1G`) are hardcoded as module constants in the test file — no env vars needed.

## Design decisions

- **CubeSandbox SDK only** (no dual-backend parameterization): E2B SDK's template API uses a completely different endpoint format (`/v3/templates` with Dockerfile) that CubeAPI does not implement. E2B SDK compatibility is sandbox-operations-only. Template alias is a CubeSandbox feature inspired by E2B concepts, not an E2B SDK wire-compatible implementation.
- **No `CUBE_TEMPLATE_E2E_IMAGE` / `CUBE_TEMPLATE_E2E_WRITABLE_LAYER_SIZE` env vars**: hardcoded defaults in the test module. Only `CUBE_TEMPLATE_ID` (already required by the framework) is needed.

## Tests

| Test | What it covers |
|---|---|
| `test_template_list_and_get_existing` | List templates + GET by ID |
| `test_template_create_from_image_and_cleanup` | Create from image + cleanup |
| `test_template_alias_dedicated_endpoint_rejects_invalid` | Invalid alias → 400 (no template creation) |
| `test_template_alias_create_get_and_delete` | Full alias lifecycle: create → get by alias → delete by alias → 404 |
| `test_template_alias_dedicated_lookup_endpoint` | `GET /templates/aliases/:alias` endpoint |
| `test_template_alias_rebuild_reassignment` | Rebuild with same alias → alias moves to newly READY template |

Verified against a live one-click deployment: **6 passed in 55s**.

Assisted-by: OhMyPi:zai/glm-5.2

### CODE REVIEW

File: tests/e2e/sdk_compat/framework/config.py [hunk 1]
```diff
@@ -85,6 +87,12 @@ def from_env(
                 os.environ.get("SDK_E2E_PLATFORM_LIFECYCLE_POLL_TIMEOUT", "45")
             ),
             cube_proxy_admin_port=int(os.environ.get("CUBE_PROXY_ADMIN_PORT", "8082")),
+            cube_template_e2e_image=os.environ.get(
+                "CUBE_TEMPLATE_E2E_IMAGE", "mirror.ccs.tencentyun.com/library/busybox:latest"
```
Comment (lkml-likexu) [inline tests/e2e/sdk_compat/framework/config.py]: Use cube-sandbox/sandbox-code:latest ?
